# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('salario', models.FloatField()),
                ('carga_horaria', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
