# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='carga_horaria',
        ),
        migrations.AddField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('CLT', 'Consolidação das Leis do Trabalho')], default='CLT', max_length=50),
            preserve_default=False,
        ),
    ]
